---
driver:
  name: vagrant
  customize:
    memory: 512
    cpuexecutioncap: 90
    cpus: 1

provisioner:
  name: chef_solo

platforms:
#  - name: ubuntu-14.04
  - name: centos-7.0
  - name: ubuntu-15.04

suites:
  - name: default

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[kagent::default]
      - recipe[kagent::test]
    attributes:
         kagent:
            dashboard:
               user: "hopagent@sics.se"
               password: "hopagent"
            rest_api:
               user: "hopagent@sics.se"
               password: "hopagent"
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            dir: "/tmp"
            use_systemd: "true"
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "true"
